CREATE TABLE IF NOT EXISTS Beats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    genre VARCHAR(120) NOT NULL,
    userId INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_beats_user FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);
